# Generated by Django 3.2.1 on 2021-05-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='about',
            new_name='description',
        ),
    ]
